// Code generated by "stringer -linecomment -type=IdentityVersion"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IdentityVersionUnknown-0]
	_ = x[IdentityVersion1-3657731179]
}

const (
	_IdentityVersion_name_0 = "IDENTITY_UNKNOWN"
	_IdentityVersion_name_1 = "IDENTITY_V1"
)

func (i IdentityVersion) String() string {
	switch {
	case i == 0:
		return _IdentityVersion_name_0
	case i == 3657731179:
		return _IdentityVersion_name_1
	default:
		return "IdentityVersion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
