// Code generated by "stringer -linecomment -type=MessageType"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MessageTypeUnknown-0]
	_ = x[MessageTypeClientHello-257]
	_ = x[MessageTypeServerHello-258]
	_ = x[MessageTypeSyncRequest-513]
	_ = x[MessageTypeSyncResponse-514]
}

const (
	_MessageType_name_0 = "MSG_UNKNOWN"
	_MessageType_name_1 = "MSG_CLIENT_HELLOMSG_SERVER_HELLO"
	_MessageType_name_2 = "MSG_SYNC_REQUESTMSG_SYNC_RESPONSE"
)

var (
	_MessageType_index_1 = [...]uint8{0, 16, 32}
	_MessageType_index_2 = [...]uint8{0, 16, 33}
)

func (i MessageType) String() string {
	switch {
	case i == 0:
		return _MessageType_name_0
	case 257 <= i && i <= 258:
		i -= 257
		return _MessageType_name_1[_MessageType_index_1[i]:_MessageType_index_1[i+1]]
	case 513 <= i && i <= 514:
		i -= 513
		return _MessageType_name_2[_MessageType_index_2[i]:_MessageType_index_2[i+1]]
	default:
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
