// Code generated by "stringer -linecomment -type=ProtocolVersion"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProtocolVersionUnknown-0]
	_ = x[ProtocolVersion1-1348853002]
	_ = x[ProtocolVersion1Encrypted-2103431722]
}

const (
	_ProtocolVersion_name_0 = "PROTOCOL_UNKNOWN"
	_ProtocolVersion_name_1 = "PROTOCOL_V1"
	_ProtocolVersion_name_2 = "PROTOCOL_V1_ENCRYPTED"
)

func (i ProtocolVersion) String() string {
	switch {
	case i == 0:
		return _ProtocolVersion_name_0
	case i == 1348853002:
		return _ProtocolVersion_name_1
	case i == 2103431722:
		return _ProtocolVersion_name_2
	default:
		return "ProtocolVersion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
